### ISSUE TITLE
I made an interactive version of this image :)

### ISSUE THREAD

**Issue by nikivdev** [godrm/mobile-developer-roadmap#1]
[Take a look](https://my.mindnode.com/m32Zo1SzPiqfWqJvpUwBMuTMCNVXejfyWfZyeSFz#61.8,204.1,2). :)

Thank you a lot for sharing this. It's part of a bigger [mind map](https://github.com/nikitavoloboev/knowledge-map) too.

**Comment by godrm** [comment]
I'm so sorry that I did't know this issue. 
Thank you so much your great work. Awesome!
